// this file is index.js with next.js. Here you can do anything as if it were index.js

import type { Metadata } from "next";
import { Inter } from "next/font/google";

//import react because this file is a module
import React from "react";
//Provider
import { StoreProvider } from "../store/StoreProvider";
// styles
import "../styles/styles.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My react project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </StoreProvider>
  );
}
